"use client";

//import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import ClientNavbar from "./navbar/clientNavbar";
import { store } from "@/store";
// import store from "@/store";

// // Define the Inter font loader at the top level
// const inter = Inter({ subsets: ["latin"] });

// // Metadata for the app (if needed)
// export const metadata = {
//   title: "Skill Capital",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <title>Skill Capital</title>
      </head>
      <body>
        <Provider store={store}>
          <ClientNavbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
